version: '3.1'

services:
  postgresql:
    image: postgres:13.2-alpine
    ports:
      - 5001:5432
    environment:
      - POSTGRES_DB=fastoffer
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - fastoffer
    volumes:
      - type: volume
        source: fastoffer-data
        target: /var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    ports:
    - 5002:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - fastoffer

networks:
  fastoffer:

volumes:
  fastoffer-data: